//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/ControlMapping.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlMapping: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlMapping()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlMapping"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""ba325ada-bcfd-4add-826a-96af20b92ec7"",
            ""actions"": [
                {
                    ""name"": ""Connect"",
                    ""type"": ""Button"",
                    ""id"": ""c5b3c1e5-869a-43ff-ad43-96b0673ecb87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shop1"",
                    ""type"": ""Button"",
                    ""id"": ""d8d58acb-c167-4051-a3d9-4b778b3f90d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shop2"",
                    ""type"": ""Button"",
                    ""id"": ""70d30f1a-679a-442f-8589-bc803fee9f9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shop3"",
                    ""type"": ""Button"",
                    ""id"": ""50048905-64a1-4c4b-aae2-d58cd2721c55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shop4"",
                    ""type"": ""Button"",
                    ""id"": ""6503b55b-4950-4f80-bd41-af17d008bf48"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveGhost"",
                    ""type"": ""Value"",
                    ""id"": ""eb5c47aa-e63a-46fd-a899-fec2f7ce4824"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""75d03985-3008-45d7-be7a-6055bb46d480"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Connect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""132537d1-41ee-4b42-9a02-3a5c6396ef36"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Connect"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""2510d6a6-983a-4282-93eb-b7f5ef5d2430"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Connect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""372ab676-3735-4248-bda4-9dba37810aa0"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Connect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""de65055c-8efd-4fdc-b92d-bff8647f9742"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shop1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94e50b7b-c56e-4be4-bad1-0b7ba7cb572c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shop1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""daf1746a-f6ca-491a-a577-23da6eb468e7"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shop2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb8c3c1a-7b9c-428b-bfbf-761a8bd05242"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shop2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a61738d0-9a2f-446c-9406-8f96d0ea57ca"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shop3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47e435ae-30b7-476c-8f12-0fd0b45493ec"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shop3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85d1965b-0f6f-44e6-ba7e-647f05e42408"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shop4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""956b4bb4-c641-4d83-b8f9-f0d794b346a5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shop4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d8777b47-c430-40b2-825e-65636a51cf4a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGhost"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a88aec3a-b52f-4ab1-bda1-929b8dc1eac0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGhost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5d0cf583-92a3-4e42-b948-8dbff1115a5f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGhost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b3708b10-0dd7-443d-a393-dad7cf32e155"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGhost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""18c3d6d9-a6dc-4575-be47-b7b801a5214f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGhost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4b46a9bd-5bea-4484-801c-ec61205419a9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGhost"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""dc5948f0-c292-45a0-88de-016ee4dd3dcf"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGhost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""35dbec0d-72da-4455-9ed6-dbb4c584e8bb"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGhost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""26a9582f-7fae-4f75-9bd8-91942eda6b48"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGhost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5b0437e8-e209-4fb1-8bc8-884f75d14bd9"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveGhost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Connect = m_Player.FindAction("Connect", throwIfNotFound: true);
        m_Player_Shop1 = m_Player.FindAction("Shop1", throwIfNotFound: true);
        m_Player_Shop2 = m_Player.FindAction("Shop2", throwIfNotFound: true);
        m_Player_Shop3 = m_Player.FindAction("Shop3", throwIfNotFound: true);
        m_Player_Shop4 = m_Player.FindAction("Shop4", throwIfNotFound: true);
        m_Player_MoveGhost = m_Player.FindAction("MoveGhost", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Connect;
    private readonly InputAction m_Player_Shop1;
    private readonly InputAction m_Player_Shop2;
    private readonly InputAction m_Player_Shop3;
    private readonly InputAction m_Player_Shop4;
    private readonly InputAction m_Player_MoveGhost;
    public struct PlayerActions
    {
        private @ControlMapping m_Wrapper;
        public PlayerActions(@ControlMapping wrapper) { m_Wrapper = wrapper; }
        public InputAction @Connect => m_Wrapper.m_Player_Connect;
        public InputAction @Shop1 => m_Wrapper.m_Player_Shop1;
        public InputAction @Shop2 => m_Wrapper.m_Player_Shop2;
        public InputAction @Shop3 => m_Wrapper.m_Player_Shop3;
        public InputAction @Shop4 => m_Wrapper.m_Player_Shop4;
        public InputAction @MoveGhost => m_Wrapper.m_Player_MoveGhost;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Connect.started += instance.OnConnect;
            @Connect.performed += instance.OnConnect;
            @Connect.canceled += instance.OnConnect;
            @Shop1.started += instance.OnShop1;
            @Shop1.performed += instance.OnShop1;
            @Shop1.canceled += instance.OnShop1;
            @Shop2.started += instance.OnShop2;
            @Shop2.performed += instance.OnShop2;
            @Shop2.canceled += instance.OnShop2;
            @Shop3.started += instance.OnShop3;
            @Shop3.performed += instance.OnShop3;
            @Shop3.canceled += instance.OnShop3;
            @Shop4.started += instance.OnShop4;
            @Shop4.performed += instance.OnShop4;
            @Shop4.canceled += instance.OnShop4;
            @MoveGhost.started += instance.OnMoveGhost;
            @MoveGhost.performed += instance.OnMoveGhost;
            @MoveGhost.canceled += instance.OnMoveGhost;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Connect.started -= instance.OnConnect;
            @Connect.performed -= instance.OnConnect;
            @Connect.canceled -= instance.OnConnect;
            @Shop1.started -= instance.OnShop1;
            @Shop1.performed -= instance.OnShop1;
            @Shop1.canceled -= instance.OnShop1;
            @Shop2.started -= instance.OnShop2;
            @Shop2.performed -= instance.OnShop2;
            @Shop2.canceled -= instance.OnShop2;
            @Shop3.started -= instance.OnShop3;
            @Shop3.performed -= instance.OnShop3;
            @Shop3.canceled -= instance.OnShop3;
            @Shop4.started -= instance.OnShop4;
            @Shop4.performed -= instance.OnShop4;
            @Shop4.canceled -= instance.OnShop4;
            @MoveGhost.started -= instance.OnMoveGhost;
            @MoveGhost.performed -= instance.OnMoveGhost;
            @MoveGhost.canceled -= instance.OnMoveGhost;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnConnect(InputAction.CallbackContext context);
        void OnShop1(InputAction.CallbackContext context);
        void OnShop2(InputAction.CallbackContext context);
        void OnShop3(InputAction.CallbackContext context);
        void OnShop4(InputAction.CallbackContext context);
        void OnMoveGhost(InputAction.CallbackContext context);
    }
}
